/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./app.js"],
  theme: {
    extend: {
      colors: {
        primary: "#003e7a",
        "primary-container": "#0055a4",
        "primary-fixed": "#d5e3ff",
        "primary-fixed-dim": "#a8c8ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#afccff",
        secondary: "#006d33",
        "secondary-container": "#75f999",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#007236",
        tertiary: "#83000a",
        "tertiary-container": "#af0011",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        background: "#fcf9f8",
        "on-background": "#1c1b1b",
        surface: "#fcf9f8",
        "surface-bright": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "surface-variant": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#424751",
        outline: "#727783",
        "outline-variant": "#c2c6d3",
      },
      fontFamily: {
        display: ["Anybody", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
    },
  },
  plugins: [],
};
